### ISSUE TITLE
The project is not enabled for Jenkins. Missing .jenkins file.

### ISSUE THREAD

**Issue by pmartindev** [alefragnani/vscode-jenkins-status#27]
I have a workspace with the following directory structure:

```
Programming
    Github
        mydatabaseinstance
            .jenkins
            Jenkinsfile
            provision.template
```

When I open the provision.template file in the editor, and run the `Jenkins: Update Status` command, I get the following errror:

`The project is not enabled for Jenkins. Missing .jenkins file.`

**Comment by alefragnani** [comment]
Hi @pmartindev 

Is `.jenkins` a file or folder/directory? The extension expects a `.jenkins` file in the root folder of the opened project, with this minimal info:

```json
{
    "url": "http://127.0.0.1:8080/job/myproject"
}
```

Hope this helps

**Comment by alefragnani** [comment]
Hi @pmartindev , 

The `.Jenkins` file needs to be at the root folder of the opened project (the folder that you open in VS Code). So, in order for the extension to work properly, you have to open `mydatabaseinstance` folder in VS Code, otherwise, it won't work.

If I did understand correctly, you opened `Programming` in VS Code, so that appears to be the reason for the error message.

Is this your scenario?

**Comment by pmartindev** [comment]
Yep, I opened just the `mydatabaseinstance` folder and it worked, thanks!

**Comment by alefragnani** [comment]
Good to know it worked 🎉  

The reason for this _model_ is [commented here](https://github.com/alefragnani/vscode-jenkins-status/issues/9#issuecomment-296445019), and the issue is opened, to change the behavior. Feel free to upvote #9 so I could identify which features are more important

Hope this helps
