### ISSUE TITLE
Using `.jenkinsrc.js` to load credentials from $HOME/.jenkins or $ENV_VARIABLES?

### ISSUE THREAD

**Issue by curiousdev** [alefragnani/vscode-jenkins-status#59]
When jumping between many repos, its handy to have corresponding Jenkin's build right at the ready. However, we need to leave credentials in the config file. 

If we were to switch to the `*.js` example configuration, could we load our Username and SecurityToken from a configuration file?

**Comment by curiousdev** [comment]
For example, could we use `process.env`?

```javascript
// can also return a promise of required JSON structure
module.exports = [{
    "url": "http://127.0.0.1:8080/job/myproject/",
    "name": "Jenkins Build",
    "username": process.env.JENKINS_USERNAME
    "password": process.env.JENKINS_TOKEN
}];

```

**Comment by curiousdev** [comment]
I tried the above example and encountered `Error while retrieving Jenkins settings`. 

What am I overlooking?

**Comment by alefragnani** [comment]
Hi @curiousdev ,

I’m not able to test it right now, but you could try to use the _dynamic import_ approach as exemplified on the original PR https://github.com/alefragnani/vscode-jenkins-status/pull/17#issuecomment-587417349

Instead of directly using `process.env.SOME_ENV`, try loading its value and populating the setting.

Try looking at `Console` in `Developer Tools` to see if the extension raises any error.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
